CREATE TABLE IF NOT EXISTS train_orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Header fields (underlined blanks on the form)
    order_number        VARCHAR(20),
    form_type           VARCHAR(20),
    from_location       VARCHAR(200),
    order_date          VARCHAR(30),
    to_line             VARCHAR(2000),
    operator_initials   VARCHAR(50),
    time_issued         VARCHAR(20),
    at_location         VARCHAR(500),
    dispatcher_initials VARCHAR(50),
    -- Large instructions body (centre of the form)
    instructions        CLOB,
    -- Completion section
    complete_time       VARCHAR(20),
    complete_operator   VARCHAR(50),
    -- Recopy section
    recopied_by         VARCHAR(200),
    recopy_operator     VARCHAR(50),
    recopy_date         VARCHAR(30),
    -- Lifecycle
    completed           BOOLEAN DEFAULT FALSE,
    -- Metadata
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

